# Generated by Django 2.2.4 on 2019-08-16 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190816_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='autohor',
            new_name='author',
        ),
    ]
